import { useState } from "react";
import { ArrowRight, BookOpen, Check, ChevronDown, CircleHelp, Lightbulb, MapPin, Sparkles } from "lucide-react";

const faqs = [
  ["از کجا شروع کنم؟", "از «پروژه جدید» شروع کن، نام و شرح ایده را وارد کن و نوع ارائه را مشخص کن. برنامه بعد از آن پرسش‌های متناسب با کسب‌وکار تو را می‌سازد."],
  ["آیا لازم است به همه سؤال‌ها پاسخ دقیق بدهم؟", "نه؛ اگر هنوز اطلاعات کافی نداری، گزینه «هنوز نمی‌دانم» را انتخاب کن. همین کمبود اطلاعات به یک فرضیه یا آزمایش برای مرحله بعد تبدیل می‌شود."],
  ["تفاوت کسب‌وکار حضوری و آنلاین در برنامه چیست؟", "در کسب‌وکار حضوری یا ترکیبی، موقعیت، پاخور و رقبای محدوده بررسی می‌شود. در کسب‌وکار کاملاً آنلاین، نقشه حذف و به‌جای آن رقبای مجازی با شاخص‌هایی مانند دسترسی، نرخ تعامل و نرخ تبدیل سنجیده می‌شوند."],
  ["اطلاعات من کجا ذخیره می‌شود؟", "در نسخه Demo اطلاعات در LocalStorage همین مرورگر ذخیره می‌شود و بین دستگاه‌ها همگام نیست. برای جابه‌جایی می‌توانی از دانلود و بازیابی پشتیبان JSON استفاده کنی."],
  ["چطور از هوش مصنوعی استفاده کنم؟", "در پایان پرسشنامه، برنامه پرامپت کامل را آماده و کپی می‌کند. آن را در Claude، ChatGPT یا Gemini قرار بده، پاسخ را کپی کن و با گزینه چسباندن پاسخ داخل برنامه برگردان."],
  ["امتیاز اعتبارسنجی به چه معناست؟", "امتیاز، کیفیت شواهد ثبت‌شده در پروژه را نشان می‌دهد، نه تضمین موفقیت کسب‌وکار. شواهد رفتاری مانند پیش‌پرداخت و خرید واقعی از نظرهای کلی ارزش بیشتری دارند."],
  ["گزارش PDF چه چیزهایی دارد؟", "پاسخ‌های پرسشنامه، تحلیل AI، اطلاعات موقعیت یا رقبای مجازی، آزمایش‌ها و تحلیل مالی در گزارش چاپی قرار می‌گیرند. از گزینه خروجی گزارش و سپس چاپ مرورگر، ذخیره به‌صورت PDF را انتخاب کن."],
  ["چطور پروژه را به دستگاه دیگری منتقل کنم؟", "از منوی پایین نوار کناری «دانلود پشتیبان JSON» را بزن. فایل را به دستگاه دیگر منتقل کن و از همان منو «بازیابی از JSON» را انتخاب کن."],
];

export function HelpCenter({ onBack }: { onBack: () => void }) {
  const [openFaq, setOpenFaq] = useState<number | null>(null);
  return <section className="help-page"><div className="page-heading"><div><div className="eyebrow">راهنما و پشتیبانی داخل برنامه</div><h1>چطور با اعتبارسنج کار کنم؟</h1><p>این راهنما کمک می‌کند از ایده خام به شواهد قابل تصمیم‌گیری برسی.</p></div><button className="ghost-button" onClick={onBack}><ArrowRight size={16} /> بازگشت به داشبورد</button></div><div className="help-steps"><article><span className="help-step-icon"><Lightbulb size={19} /></span><b>۱. پروژه بساز</b><p>هویت، ایده، نوع کسب‌وکار و شیوه ارائه را وارد کن.</p></article><article><span className="help-step-icon"><CircleHelp size={19} /></span><b>۲. به سؤال‌ها پاسخ بده</b><p>پاسخ‌ها را بر اساس رفتار واقعی مشتری انتخاب کن، نه حدس خوش‌بینانه.</p></article><article><span className="help-step-icon"><MapPin size={19} /></span><b>۳. رقبا را بررسی کن</b><p>برای مدل حضوری نقشه و برای مدل آنلاین شاخص‌های رقابت دیجیتال را ثبت کن.</p></article><article><span className="help-step-icon"><Sparkles size={19} /></span><b>۴. آزمایش و گزارش</b><p>آزمایش کم‌هزینه طراحی کن، نتیجه را ثبت کن و گزارش را دریافت کن.</p></article></div><div className="help-content"><div className="help-guide-card"><div className="section-heading"><div><div className="card-kicker"><BookOpen size={15} /> راهنمای عملی</div><h2>اصل مهم اعتبارسنجی</h2></div><Check size={18} /></div><blockquote>هدف برنامه پیش‌بینی قطعی موفقیت نیست؛ هدف، پیدا کردن مهم‌ترین ریسک و آزمایش آن با کمترین هزینه است.</blockquote><ul><li>به‌جای «آیا این ایده خوب است؟» درباره آخرین رفتار واقعی مشتری بپرس.</li><li>قبل از ساخت کامل، یک تعهد کوچک مانند پیش‌ثبت‌نام، پیش‌فروش یا اجرای دستی خدمت بگیر.</li><li>برای هر آزمایش، معیار موفقیت و بازه زمانی را قبل از اجرا مشخص کن.</li><li>داده‌های نامطمئن را با برچسب «برآورد» ثبت کن و آن‌ها را با واقعیت اشتباه نگیر.</li></ul></div><div className="help-faq-card"><div className="section-heading"><div><div className="card-kicker"><CircleHelp size={15} /> پاسخ‌های سریع</div><h2>پرسش‌های متداول</h2></div></div><div className="faq-list">{faqs.map(([question, answer], index) => <div className={`faq-item ${openFaq === index ? "open" : ""}`} key={question}><button onClick={() => setOpenFaq(openFaq === index ? null : index)}><span>{question}</span><ChevronDown size={17} /></button>{openFaq === index && <p>{answer}</p>}</div>)}</div></div></div></section>;
}
